version: "3.7"

services:
    server:
        build:
            context: ./
            target: production-build-stage
        ports:
            - "${APP_PORT:-3000}:3000"
        # volumes:
        #     - ./:/app
        #     - /app/node_modules
        restart: "unless-stopped"
        environment:
            TYPEORM_HOST: "mysql"
        networks:
            - backend
        depends_on:
            - mysql
            - redis

    mysql:
        image: "mysql:latest"
        environment:
            MYSQL_ROOT_PASSWORD: "${TYPEORM_PASSWORD}"
            MYSQL_DATABASE: "${TYPEORM_DATABASE}"
            MYSQL_PASSWORD: "${TYPEORM_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        volumes:
            - "backendmysql:/var/lib/mysql"
        networks:
            - backend
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

    redis:
        image: "redis:latest"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "backendredis:/data"
        networks:
            - backend
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

networks:
    backend:
        driver: bridge

volumes:
    backendmysql:
        driver: local
    backendredis:
        driver: local
